database:
  host: postgres
  port: 5432
  user: ecommerce
  password: ecommerce
  name: ecommerce
  sslmode: disable
  timezone: UTC
  max_open_conns: 50
  max_idle_conns: 10
  conn_max_minutes: 5
admin_api_key: "dev-admin-key-123"
audio_storage:
  path: "/app/data/audio_contacts"
  base_url: "https://localhost:9997/api"
  max_payload_size_mb: 10
ratelimit:
  default:
    post: 300
    get: 900
  controllers:
    contactus:
      post: 900
      get: 300
    audiocontact:
      post: 60  # Limit audio submissions to 1 per minute
      get: 300 